export const validationSettings = {
  formSelector: ".modal__container",
  inputSelector: ".modal__input",
  submitButtonSelector: ".modal__button",
  inactiveButtonClass: "modal__button_disabled",
  inputErrorClass: "modal__input_type_error",
  errorClass: "modal__error_visible",
};

export const config = {
  cardNameField: "#card-name",
  cardLinkField: "#card-link",
  profileTitleInput: ".modal__input",
  profileDescriptionInput: ".modal__description",
  imagePopup: "#image-modal",
  cardAddPopup: "#add-card-modal",
  cardAddForm: "#add-card-form",
  cardGallery: ".cards__gallery",
  cardSelector: "#card-template",
  profileDescriptionSelector: ".profile__subtitle",
  profileNameSelector: ".profile__title",
  profileFormSelector: "#modal-profile-form",
  profileEditClose: ".modal__close",
  profileEditPopup: "#edit-modal",
  cardAddCloseButton: ".modal__close",
  imagePreviewClose: "#image-close",
  profileEditOpen: ".profile__edit",
  cardAddButton: "#add-button",
  profileModalSelector: ".modal",
  formSelector: ".modal__container",
  popupSelector: ".modal__opened",
  avatarSelector: ".profile__avatar",
};
